import streamlit as st

# Schizophrenia Section
st.title("Schizophrenia: Understanding and Detection")

## Introduction
st.header("Introduction")
st.write(
    """
Schizophrenia is a multifaceted mental disorder characterized by episodes of psychosis, encompassing symptoms such as hallucinations, disorganized thinking and speech, social withdrawal, delusions, impaired emotional expression, and cognitive deficits. While its exact cause remains elusive, existing evidence suggests a complex interplay of genetic, biological, and environmental factors. The diagnostic process involves meeting specific criteria outlined in manuals like the DSM-5, with symptoms persisting for a certain duration. The initial manifestation of psychosis in an individual later diagnosed with schizophrenia is termed a first-episode psychosis (FEP). It is crucial to consider various symptoms when comprehensively understanding this disorder.
"""
)

## Electroencephalography (EEG) Section
st.header("Electroencephalography (EEG)")

### EEG Overview
st.write(
    """
EEG is a medical test that records electrical activity in the brain. This test is performed by attaching small electrodes to the scalp, which detect and measure the electrical impulses generated by brain cells, or neurons. The resulting recording, called an electroencephalogram, reflects the brain's electrical activity and can provide valuable information about brain function.

Electroencephalogram (EEG) is an avenue being experimentally utilized due to its ability to record and analyze the brain's electrical activity as a way to detect schizophrenia. In these experiments, researchers often employ sophisticated techniques such as frequency analysis, microstates, event-related potentials, and measures of entropy. These features are commonly used to discern patterns in the EEG recordings, revealing differences between healthy control subjects and individuals diagnosed with schizophrenia.
"""
)


# Continue adding subsections for Theta, Alpha, Beta, and Gamma frequencies...

# References Section
st.header("References")
st.markdown(
    """
- Perrottelli, A., Giordano, G. M., Brando, F., Giuliani, L., & Mucci, A. (2021). EEG-Based Measures in At-Risk Mental State and Early Stages of Schizophrenia: A Systematic Review. [Frontiers in Psychiatry](https://www.frontiersin.org/articles/10.3389/fpsyt.2021.653642/full)

- WebMD Editorial Contributors. (2022, January 21). Schizophrenia: An Overview. [WebMD](https://www.webmd.com/schizophrenia/mental-health-schizophrenia)

- Schizophrenia. [Wikipedia](https://en.wikipedia.org/wiki/Schizophrenia)

- Electroencephalography. [Wikipedia](https://en.wikipedia.org/wiki/Electroencephalography)
"""
)
