import streamlit as st

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pyedflib import highlevel

# Schizophrenia Section
st.title("Schizophrenia: Understanding and Detection")

## Introduction
st.header("Introduction")
st.write(
    """
    Schizophrenia is a multifaceted mental disorder characterized by episodes of psychosis, encompassing symptoms such as hallucinations, disorganized thinking and speech, social withdrawal, delusions, impaired emotional expression, and cognitive deficits. While its exact cause remains elusive, existing evidence suggests a complex interplay of genetic, biological, and environmental factors. The diagnostic process involves meeting specific criteria outlined in manuals like the DSM-5, with symptoms persisting for a certain duration. The initial manifestation of psychosis in an individual later diagnosed with schizophrenia is termed a first-episode psychosis (FEP). It is crucial to consider various symptoms when comprehensively understanding this disorder.
"""
)

## Electroencephalography (EEG) Section
st.header("Electroencephalography (EEG)")

### EEG Overview
st.write(
    """
EEG is a medical test that records electrical activity in the brain. This test is performed by attaching small electrodes to the scalp, which detect and measure the electrical impulses generated by brain cells, or neurons. The resulting recording, called an electroencephalogram, reflects the brain's electrical activity and can provide valuable information about brain function.

Electroencephalogram (EEG) is an avenue being experimentally utilized due to its ability to record and analyze the brain's electrical activity as a way to detect schizophrenia. In these experiments, researchers often employ sophisticated techniques such as frequency analysis, microstates, event-related potentials, and measures of entropy. These features are commonly used to discern patterns in the EEG recordings, revealing differences between healthy control subjects and individuals diagnosed with schizophrenia.
"""
)


# Continue adding subsections for Theta, Alpha, Beta, and Gamma frequencies...

# References Section
st.header("References")
st.markdown(
    """
- Perrottelli, A., Giordano, G. M., Brando, F., Giuliani, L., & Mucci, A. (2021). EEG-Based Measures in At-Risk Mental State and Early Stages of Schizophrenia: A Systematic Review. [Frontiers in Psychiatry](https://www.frontiersin.org/articles/10.3389/fpsyt.2021.653642/full)

- WebMD Editorial Contributors. (2022, January 21). Schizophrenia: An Overview. [WebMD](https://www.webmd.com/schizophrenia/mental-health-schizophrenia)

- Schizophrenia. [Wikipedia](https://en.wikipedia.org/wiki/Schizophrenia)

- Electroencephalography. [Wikipedia](https://en.wikipedia.org/wiki/Electroencephalography)
"""
)
st.header("EEG Data Analysis")

# Load EEG data into a DataFrame
eeg_df = pd.read_csv("Acquired Dataset/participant_info.csv")

# Number of Patients and Controls
num_patients = eeg_df[eeg_df["category"] == "Patient"].shape[0]
num_controls = eeg_df[eeg_df["category"] == "Control"].shape[0]

# Male to Female Ratio
male_to_female_ratio = eeg_df["sex"].value_counts()

# Male Patients to Female Patients Ratio
male_patients = eeg_df[
    (eeg_df["category"] == "Patient") & (eeg_df["sex"] == "M")
].shape[0]
female_patients = eeg_df[
    (eeg_df["category"] == "Patient") & (eeg_df["sex"] == "F")
].shape[0]
male_to_female_patients_ratio = (
    male_patients / female_patients if female_patients != 0 else "N/A"
)

# Male Controls to Female Controls Ratio
male_controls = eeg_df[
    (eeg_df["category"] == "Control") & (eeg_df["sex"] == "M")
].shape[0]
female_controls = eeg_df[
    (eeg_df["category"] == "Control") & (eeg_df["sex"] == "F")
].shape[0]
male_to_female_controls_ratio = (
    male_controls / female_controls if female_controls != 0 else "N/A"
)

# Age Distribution for Controls and Patients
age_distribution_controls = eeg_df[eeg_df["category"] == "Control"]["age"].describe()
age_distribution_patients = eeg_df[eeg_df["category"] == "Patient"]["age"].describe()

# Display Results
st.write(f"Number of Patients: {num_patients}")
st.write(f"Number of Controls: {num_controls}")
st.write(f"Male to Female Ratio:\n{male_to_female_ratio}")
st.write(f"Male Patients to Female Patients Ratio: {male_to_female_patients_ratio}")
st.write(f"Male Controls to Female Controls Ratio: {male_to_female_controls_ratio}")
st.write(f"\nAge Distribution for Controls:\n{age_distribution_controls}")
st.write(f"\nAge Distribution for Patients:\n{age_distribution_patients}")

st.write("\n### EEG data measurement is done in four phases:")
st.write("1. **Rest Phase 1:** Participants were at rest.")
st.write("2. **Arithmetic Phase:** Participants performed arithmetic tasks.")
st.write("3. **Rest Phase 2:** Another rest period.")
st.write("4. **Auditory Task Phase:** Participants performed an auditory task.")

st.write("This was done multiple times.")
st.write("""Fp1, Fp2: Frontopolar (Frontoparietal) electrodes.
F3, F4: Frontal electrodes.
C3, C4: Central electrodes.
P3, P4: Parietal electrodes.
O1, O2: Occipital electrodes.
F7, F8: Frontotemporal electrodes.
T3, T4: Temporal electrodes.
T5, T6: Temporal/parietal electrodes.
Fz, Pz, Cz: Midline electrodes, corresponding to the frontal (Fz), parietal (Pz), and central (Cz) regions.
Pg1, Pg2: Parietal/occipital electrodes.
EOGR: Electrooculogram Right (measuring eye movement).
EOOGL: Electrooculogram Left (measuring eye movement).
EMG: Electromyogram (measuring muscle activity).""")